env = PATH,$PATH:$HOME/.local/bin

exec-once = pgrep -x ocrpeeker || ocrpeeker

bind = CTRL SHIFT, P, exec, ocrpeeker-client capture
bind = CTRL SHIFT, X, exec, ocrpeeker-client toggle
bind = CTRL SHIFT, Q, exec, ocrpeeker-client quit
